version: '3.1'

networks:
  bdd-network:
    driver: bridge

services:
  db:
    image: postgis/postgis:16-3.4
    restart: always

    networks:
      - bdd-network
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    networks:
      - bdd-network
    ports:
      - 80:8080
    depends_on:
      - db
